server:
  port: 9090

spring:
  application:
    name: second-web
  datasource:
    url: jdbc:mysql://localhost:3306/javaOdev2
    username: root
    password: hSelMan%231?!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

